language: java
jdk:
  - "oraclejdk8"

sudo: required
group: edge

before_install:
  - sleep 15

services:
  - mongodb
  - docker

env:
  global:
    - TERM=dumb

script: mvn clean install

after_success:
  - mvn install -DskipTests=true -Pdocker
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && .
  - echo "SHOULD NOT COME HERE"