language: java
jdk:
- oraclejdk8

sudo: required
group: edge
dist: trusty

services:
  - mongodb
  - docker

addons:
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - TERM=dumb
  - secure: "EvRtQsJ3po1cKD8MPXHcGwAK6g3aBJ+MEMg4lc1Vm/L8HRXwnI/RDCWzOI7zMZI/vvvdeeifeeiRpaED+tQk1zK49rp+N19v0EBj3CeYNupfU2JwnTVgGrpxeMoCOWorQWJ2JXPJisjlrK5GAJb5JvkcJlYoDlEMUUikWfLAKZAFIpXeWnzgE0B1qw4CHZImt722EiJFszngW467Oh5xu5NHpVMrQXI9cNUxWR1fP/c4Tci4pzvm1rHsWf1iQLjzCGNv9frXteu+VdrzUHLDfGZDEPrWpUnncPLWLdCDS4lNhfC+xWF5H8cco23lKUZJwrpDMKHxMB6JRFsNSZ/tJYM+fw7UKq4TVP1IIVQvSe4fTs6WhTP5/AN00v9iXB5IdnyCyNafLv15eSl06OR+C8vGAOAjnX1DESmHLXyamXKYKsc/ZBXKTBE3zqN7z3y10JRLNM5jVYRpYY0v6JqZQzW2jgS+Zee4HhObZUpyFfE8pBUKAn3ztGiYNZP+x7CvXOtio/KuqNVNt4HMkzwNH+7jyFPIvaL0nPqreae1LXebB6y3lk2wisRLsMnAR5JkuF2IXgc78BzbDoiddLmp4OdZUc4tf0Qua0S0T9DunxSiRbhniKM/Qip8Pv4nYleZsptUXe7TnirxVGwVmJq4ZL3otg95w9hU2Ul/lYYg9hg=" #DOCKER_EMAIL
  - secure: "hFzsx5R1Rn20FwF+szY3WLaE2BcnqTHfwfmWrGgaXLcbyiRgrW0tc2oS6lRiaMk+yll2asJuWuoOj8pUB3/hNtV1wIMmXopBTh6tajhFB18Eq/w0E4Cfm2auq0RLd+VY4RSGTI1VYDdwiEqFvCUp6yZG1OFkXGhycN14YkiWxbler8S8ajnSE2fYBeDDQW/bkx+rEyBWSttvzAIs/6Ep3KOXueXALXA1yUD7HyG2EEHerl2F0cUCKelyfPgr5RN0gnAZHboBWBYAT4IHKMd1mpY5QI9kHzrql/pl00xD2lVjh2K06VMImKbiZXbZiV7kznBeV1S9QvCMTZkTSataGhkKJJ/gONlM1tnEXqHyXdn++XUlHcs5yvObrixQ1LYpIDa1P0WIqkNXDGPuT6sn+qKzz6IiCUSmlhGiU5or2n3ahpwN2ZiRSm/S2lV6VvQggfT246EVfuLh/YI7oQiPbUhIQwHHYEjyQ9DiwYPXt59CU1YYbdo2CAQvwNJ1lLa/x77yR6MTnagFI9Hd/V43nzs7nI9lN3Wl6JlCY2w5cOO8B5W0t1R8fc3G1eyjNMH9vgc15Iy/c1pknexzzHY0FW1+BRpiJqXDYDV32TcVVlVXm0m87mQx8u7n3gRY282XMvWQiJe5+jdQC/SIBBHXqQm4QfvDANHTT/AUeyEt1PE=" #DOCKER_USER
  - secure: "SY+mGR4k8nhDiTwrMClqVhv5WjqkohEvrXyHQiQhXy1NvYjM1FlWJ2OLCOLObCAidyyfNgVgItf3z+kUpXNStVkIhppnr+uaNsUz2ZKCGPVEp7CDW28LK1b6lPxZzBDYx4V69Ofa0j5Qcn5VTB4FaFWYIrjLICOoL3zdfB8kKlyyN2tPjrB2V+vnAjqFMwVXY6Zik3HZOVcBeAWOCwI7fSfCvA6kTDzz8CV45BwDyXKki8QG0g4Y7ZwW131MUhIbi+DyRjWBj56aq30wRurtajwnpVR8Onn2TEb3U7ARV4nQxFoVrM1obFUMEHbnUChJcvn7I/Wv7IY+WWhXTxQubQsvPhw1sWgghw13irSMfA8y37QpRGm9k8uZZ0PF6Qe7nBGPHSu+3MDJzzPC11F0+lE/FJtuEUxHH2GhBr7BfLS2qlAsqOav7ApS864JJaECjSvNpwFycVpb6p9E7rc/eIxPkPkg2hjBGDboOKsDYF7D4mdBEihAZpGLehy5ATW5Ksteaxc+7GFhyLmftwtq5RKI921/bH/kfrz81XHUlF0vUK2yYaUxFrb/iHjOZBHR/CnAV2X8j4kSHz0wmShwce+Ov98lz/2V05li27taIYfYEca5kks76XuvxfC3XFYaSH+6ewdrGMR/URUuz3Y3ipe/rgqqq3EWILcg+jEobQI=" #DOCKER_PASS
  - secure: "PccXHUeXS71Buu1EWHa47z11rLwk2oUpNqkK+LmyX4w90E5jwSfFsbb1uhYExv3z6mADkGLpoH4toYAiU38rPQxSSruFAeHegovlc2tH2rjdowfk7jzw6EYNwKgypbNCIbtSWktVKWsXSfMgbZ9JkbTHPNGBNXEW3qYNd/vCNg+Y/GeU9YZle888md4txMELbvsIAYXK0vUeH0Myno94GVnjnd4BpU5eM4OOQgP2LDwr8adov/QRMJ3w5bN4UZP46oy+rrRMZEvTvDU6O98YuKXFHv1lfO1a6xSvjOXo7B2lEOJ9YdcQi9Ht2MddUzhq8ZQlmPhtoyt+kSMc4HKUEtpXBZjKHsXgZT78rMcfhL0Nr2OfEj+RQK1LuprcBEWFMBZPNezFJXHQup65dBKI6fGLCS2+/pOj2thr2WPpQ+O6Ot1wuV6/t2CdHI4KEf8OXst0S47bBzxiMmXYYoRzcbitq2O6aHpgDGxfVXIiIcpR4w0U5mtiH71itAv5UqcSsPB/aXpGGI869etoviakiCNnOauAbrBpNpBWhsSpu+2J9ufmWysx1NLsoL6yvcAjyiWGdTh9fx6Xjx28oEimCcqb/HjmrR4+nlPFpcKA3q5H93TzNvd9z0S59DW03/sLf4szV+9NtBZmsYDLEyyts2iKsFO/jGAfHu50m+r+iIk=" #DEPLOY_HOST
  - secure: "MUlfe4dCOgLIXk6eiMIBZ4Yp31Kmo7VDsCUtM3TKorGZKvpprQTx4ZaeU4F++ObatI15CvhL6LkO185wr18IkZTk/XR4W0RSnFwET3roGKb8qy2UIvGOlylvYxbzI1X8oeou9ezu0ICJ6BJPkEBoCj9clDUoHJk6oqcRdj09l1z2nRO5v2GRXxblh093ZmdA7G6ho0T6ZSBobe4R41XcUQXU8y3/Imv/khf3x6m+SPGJPUFEptOKac23eLs2vS8rTdC+eUZarPUxkjvo5rmoxVNPCflJuJfkAqLBED6a+UNjYzEfAoAjPjh2Cd/bk//8wcDDgqA2xP1z8n6Hy/2AGMSCyZExQ2+TT43C7grKdfC8QixeOvyGl0tAgUOBijtkr+wH/FpkoGrz4SVGIi1T4ZbEg824Mb/aZmdxdV9EN0r+/jPxdeGJO2su/2YT+HkUBQnp0RAsnOzh1jTWZT6WTRiiILrttyIoDalFCF/a9kq/QwCHcSZxVbdv7kfWGsXzDGbcAB9iOBKvUCQydxehxeMhvAfwiUkyqfizxi1lVyxNh8VWilJCL8EUoHM6F7pMk41A9/NvTrOZAHXbPASJ/5H+9r1LM4CMYboPz9vDeWCLuP0PKQGuzSnAiH5DH7T5W7lDJ5HtZHQAB0exqrmRChdztCMgJHVTA/wrf9eXUV4=" #DEPLOY_PATH
  - secure: "K1N83oYsHsNiXmZAgfMlef/pUORG/ecZwD60t7cz7fWN0i4i1z3xoBXZm05wHjosA2Jf8kus0v0hyxM5jaG43+LbPLgOEvE4FsFFMQLejA9RVTOoRn9Q0SF4ytn/fBu0ctKEnNrQkbklw7hK3cHSIFuYGELrT6ju9AljHiZjLOiUFIhr/+QbiAAVgK4wUsr4doe2+NLJcXPPjLKLcmnXACPVYE9HNKun6zf+UT/vi8OQ8gsieJAPf4MvN6XueIdzKFPeraeynCDEG1nw2ZUsayLLF4XBEzfFdRExJjLBgEIcTk0wzyq2UF5WXXeZ/7S9zUloYMEqttX/uShm56oUx852Z6VBoc7k+YkN7zg8H5MbjmJBJgglsR89tBzod0Nn7iNdKi/W3az7NIWJXT9RwWj2RluxcEgpje6ZXIkX3QIvCD/Kr1saFeYb+fh/nmuTlcZx5jTSe3sdL7iQIvaQ8mRHmmTZf64UtVWajGI+TT6hWXIw9jdS601Wj3QH62oq03UHCDNk/P4deIdnDhpP+rI7b1FBXjz6QeBqwgIyS6OYMMZtKgeHwFMYfunOOLfQ086yTfiL4Myd/lIstvQ4JX6SWb3ftEFAjKmy39T4Iwfrrsha8kJD5N27KAFpSr69B7q6aO/A5b+dlS9zCTBd5Su7jQORveU2sN3SJbDz9cM=" #DEPLOY_USER
  - secure: "U2ZokSfxlmNTZOAH9+Av+x5jnpBDA5PeNDcnVNNvxTquPYwAtvkEM5uUKgxcUlYvq7+WejLPoWfmYrl7nvVLBKC1C7RqiuLb66lDYQ6XJApWr0BDW6dJpVJHYWMkfbPO6JjBlmV2l02JYhK1hPDzOr8/H9KSekyq3od1397Qy0ujTJUTNVdhqS+wiRMtePr25I/Aou5uBgW59vrV6F1Nzw7kf9bv6a3xY+mtAcRnyfXRQTfwfQ/F7/MjqN+9StKOAKZPavRBQI4VOfjLn6vQJED5Q0iaYUZX4o0bb860QiWlGeFj0y1O5KJATKcfbQ+Y0SdiVPy1SCgQZgZnofb7jKKyg0vKg570SsibN1nG0DSZv3wZjSC7jMqbQW7Ntz3HMe2Z+Ixyne4w2kZssUps2qyN+jBI582NwOb8IfU3gb+fWzCrn926DyXFBzmpl/uE5i7X9Q5ojtVp4mnlVfYJtnIwHBZ6EWdY7GksrlEV/EHXVtcSXn2IO08P9T8yx0k5ol03t6dZ6nu1R6otfnMh38dkRw/2+x7I3U9RWdyCcgGuHfl2uSN1e2Bj6dAXX22AjdptQ/LpD1LTiHin+2wmZmdEaXFXd3HZ5OjgqmoQp7b++n1rjm+q3rNubjXi3HVVSfFdpBOvrmld5MNBrddfPb0ZLMqKwTJUWFsOWpmxDEs=" #DEPLOY_PATH
  - COMMIT=${TRAVIS_COMMIT::8}
script: mvn clean install;

after_success:
  - mvn install -DskipTests=true -Pdocker
#  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH != "master" && exit
  - echo "test"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
# docker push backend
  - export BACKEND_REPO=seppaleinen/krogrouletten-backend
#  - docker build -f Dockerfile -t $BACKEND_REPO:$COMMIT .
  - docker tag $BACKEND_REPO $BACKEND_REPO:$TAG
  - docker tag $BACKEND_REPO $BACKEND_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $BACKEND_REPO
# docker push webapp
  - export WEBAPP_REPO=seppaleinen/krogrouletten-webapp
#  - docker build -f Dockerfile -t $WEBAPP_REPO:$COMMIT .
  - docker tag $WEBAPP_REPO $WEBAPP_REPO:$TAG
  - docker tag $WEBAPP_REPO $WEBAPP_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $WEBAPP_REPO
# ssh into server and run deployscript
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh