language: java
jdk:
  - "oraclejdk8"

sudo: required
dist: trusty

before_install:
  - sleep 15

services:
  - mongodb
  - docker

env:
  global:
    - TERM=dumb

script: mvn clean install

after_success:
  - mvn clean install -Pdocker
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && .
