version: "2"

services:
  nginx:
    restart: always
    build: frontend/nginx/src/main
    image: seppaleinen/krogrouletten-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt-auto:/tmp/letsencrypt-auto
      - /opt/nginx:/opt/nginx
    volumes_from:
      - webapp
    links:
      - webapp:webapp

  webapp:
    restart: always
    image: seppaleinen/krogrouletten-webapp
    expose:
      - "8000"
    links:
      - backend:backend
    volumes:
      - /webapp/application/static
    environment:
      - BACKEND_URL=http://backend:10080
      - SENTRY_DSN=https://5f31608fe1c24d2cbbf384e412c0e8c3:77adde0716644851b8d963af9d8b753e@sentry.io/98425
      - SENTRY_RELEASE=0.0.2
    command: gunicorn --config=gunicorn.config.py wsgi:app

  backend:
    image: seppaleinen/krogrouletten-backend
    restart: always
    links:
      - mongo
    environment:
      - SENTRY_DSN=https://5f31608fe1c24d2cbbf384e412c0e8c3:77adde0716644851b8d963af9d8b753e@sentry.io/98425
      - SENTRY_RELEASE=0.0.2

  mongo:
    image: mongo
    restart: always
    volumes_from:
      - data

  data:
    image: mongo
    volumes:
      - /data/db
    command: echo ''
