version: "3"

volumes:
  frontend:

services:
  nginx:
    restart: always
    build: frontend/nginx/src/main
    image: seppaleinen/krogrouletten-nginx
    ports:
      - "8081:8081"
    volumes:
      - frontend:/webapp/application/static
    networks:
      - frontend
    labels:
      - "traefik.backend=nginx"
      - "traefik.domain=docker.localhost"
      - "traefik.frontend.rule=Host:nginx.docker.localhost"
      - "traefik.frontend.entryPoints=http"
      - "traefik.enable=true"

  traefik:
    build: frontend/traefik
    image: seppaleinen/krogrouletten-traefik
    command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  webapp:
    restart: always
    image: seppaleinen/krogrouletten-webapp
    expose:
      - "8000"
    volumes:
      - frontend:/webapp/application/static
    networks:
      - frontend
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
      - SENTRY_DSN=https://5f31608fe1c24d2cbbf384e412c0e8c3:77adde0716644851b8d963af9d8b753e@sentry.io/98425
      - SENTRY_RELEASE=0.0.2
    command: gunicorn --config=gunicorn.config.py wsgi:app
    labels:
      - "traefik.backend=webapp"
      - "traefik.frontend.rule=Host:docker.localhost"

networks:
  frontend: