version: "3"

volumes:
  frontend:

services:
  nginx:
    restart: always
    build: frontend/nginx/src/main
    image: seppaleinen/krogrouletten-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
#      - /private/etc/letsencrypt:/private/etc/letsencrypt
#      - /tmp/letsencrypt-auto:/tmp/letsencrypt-auto
      - frontend:/webapp/application/static
    networks:
      - frontend

  webapp:
    restart: always
    image: seppaleinen/krogrouletten-webapp
    expose:
      - "8000"
    volumes:
      - frontend:/webapp/application/static
    networks:
      - frontend
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
      - SENTRY_DSN=https://5f31608fe1c24d2cbbf384e412c0e8c3:77adde0716644851b8d963af9d8b753e@sentry.io/98425
      - SENTRY_RELEASE=0.0.2
    command: gunicorn --config=gunicorn.config.py wsgi:app

networks:
  frontend: