[locations]
1=Location1
2=Location2
default=Location1

; These are the top-level locations that are listed in the location dropdown
; Each one points to one or more browser configurations

[Location1]
1=Browser1
2=Browser2
label="Office LAN (Virginia - IE8,Chrome,Firefox)"

[Location2]
1=Browser3
2=Browser4
label="Virginia (IE8,Chrome)"


; These are the browser-specific configurations that match the configurations
; defined in the top-level locations.  Each one of these MUST match the location
; name configured on the test agent (urlblast.ini or wptdriver.ini)

[Browser1]
browser=Nexus4 - Chrome
connection=LAN
type=nodejs,mobile
label="Nexus4 - Chrome"

[Browser2]
browser=Chrome,Firefox
label="Office LAN"

[Browser3]
browser=IE 8
label="Virginia - IE8"

[Browser4]
browser=Chrome
label="Virginia"
