[locations]
1=Office
2=Virginia
default=Office

; These are the top-level locations that are listed in the location dropdown
; Each one points to one or more browser configurations

[Office]
1=Office_IE8
2=Office_wptdriver
label="Office LAN (Virginia - IE8,Chrome,Firefox)"

[Virginia]
1=Virginia_IE8
2=Virginia_wptdriver
label="Virginia (IE8,Chrome)"


; These are the browser-specific configurations that match the configurations
; defined in the top-level locations.  Each one of these MUST match the location
; name configured on the test agent (urlblast.ini or wptdriver.ini)

[Office_IE8]
browser=IE 8
label="Office LAN - IE8"

[Office_wptdriver]
browser=Chrome,Firefox
label="Office LAN"

[Virginia_IE8]
browser=IE 8
label="Virginia - IE8"

[Virginia_wptdriver]
browser=Chrome
label="Virginia"
