version: "2"

services:
  webpagetest-manager:
    build: webpagetest-manager
    ports:
      - "80:80"
      - "443:80"
    volumes:
      - /tmp/wpt/result:/var/www/html/result

  webpagetest-agent-location1:
    build: webpagetest-agent
    privileged: true
    links:
      - webpagetest-manager:webpagetest-manager
    command: wpt/mobile/wptdriver.sh -m debug --browser chrome --serverUrl webpagetest-manager --location Browser1 --processvideo no
