name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  expo-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
