name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install dependencies
        run: mvn -B dependency:resolve
      - name: Run tests
        run: mvn test
      - name: Build docker dev image
        run: mvn install -DskipTests -Pdocker && docker-compose build
      - name: Push docker image
        env:
          dockerhub_password: ${{ secrets.dockerhub_password }}
        run: |
          docker login -u "seppaleinen" -p $( echo $DOCKERHUB_PASSWORD )
          docker push seppaleinen/krogrouletten-backend:dev
  webapp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker dev image
        run: |
          docker-compose build webapp
      - name: Tag as latest and push to dockerhub
        env:
          dockerhub_password: ${{ secrets.dockerhub_password }}
        run: |
          docker login -u "seppaleinen" -p $( echo $DOCKERHUB_PASSWORD )
          docker push seppaleinen/krogrouletten-webapp:dev
